# FILE: _config.yml
title: Book2Quiz Legal
description: Terms & Privacy for Book2Quiz
theme: jekyll-theme-cayman

# Optional: a sitemap for SEO
plugins:
  - jekyll-sitemap

# Keep clean permalinks
permalink: pretty
