# FILE: _config.yml
title: Book2Quiz Legal
description: Terms & Privacy for Book2Quiz
theme: jekyll-theme-cayman

# IMPORTANT for project sites:
url: "https://batmansunity.github.io"
baseurl: "/B2Qreleases"

# Optional: a sitemap for SEO (GitHub Pages supports this)
plugins:
  - jekyll-sitemap

# Clean URLs like /privacy/
permalink: pretty
